[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "utils"
version = "0.2.0"
description = "Personal utility python modules"
requires-python = ">=3.11"

[project.optional-dependencies]
full = [
    "cryptography",
    "pytest",
]

[tool.setuptools.packages.find]
where = ["."]
#include = ["utils*"]

[tool.setuptools.package-data]
"utils" = ["*.pyi", "py.typed"]
